# Generated by Django 3.2.9 on 2021-11-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=60)),
                ('stockDescription', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=6)),
                ('active', models.CharField(max_length=2)),
                ('skuID', models.CharField(max_length=50)),
            ],
        ),
    ]
