# Generated by Django 3.2.9 on 2021-11-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuCode', models.CharField(max_length=10)),
                ('skuDescription', models.CharField(max_length=255)),
            ],
        ),
    ]
