# Generated by Django 3.2.9 on 2021-11-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('typeID', models.CharField(max_length=2)),
                ('branchID', models.CharField(max_length=2)),
                ('token', models.CharField(max_length=60)),
            ],
        ),
    ]
